### ISSUE TITLE
Build and Calibrate the Northstar DeckX Headset

### ISSUE THREAD

**Issue by MatthewCroughan** [DoESLiverpool/somebody-should#1466]
Julian got the parts for this a few weeks ago, there's a ~~bit~~ **lot** of 3d printing that's necessary to get it done. @ajlennon is doing most of it as I do not have the filament at home to accomplish it, and he's doing it with PETG.

- The v3.1 headset BOM is [here](https://project-north-star.gitbook.io/project-north-star/mechanical/mechanical/headset-bom)
- Mechanical files are [here](https://github.com/leapmotion/ProjectNorthStar/blob/master/Mechanical/3D%20Prints.zip)

Below is a list of parts that are needed. We can check things off as needed. ~~Edit it as needed and place an `x` inside the boxes. Github does not allow markdown to be added to tables, so in order to keep the formatting of the original `.tsv` that contains quantity and description columns, I need to place it inside code blocks.~~

After some vim magic late last night I fixed the formatting so it's kind of presentable as a list

## OPTICS BRACKET 3D Prints:
- [x] 1 x # 130-001 - SIMPLIFIED OPTICS MAIN BODY - 15:37 (but I might need to do again with support which is 21:50)
- [x] 1 x # 111-002 - LEFT DISPLAY TRAY - 25cm FOCAL - 3:34
- [x] 1 x # 112-002 - RIGHT DISPLAY TRAY - 25cm FOCAL - 3:36
- [x] 1 x # 113-001 - LEFT ROTATION ADJUSTMENT SLIDE MOUNT - 0:56 
- [x] 1 x # 113-002 - LEFT CABLE GUIDE - 0:45
- [x] 1 x # 110-005 - LEFT SLIDE ENDCAP **MISSING - Advice is to print 110-006**
- [x] 1 x # 114-001 - RIGHT ROTATION ADJUSTMENT SLIDE MOUNT - 0:59
- [x] 1 x # 114-002 - RIGHT CABLE GUIDE - 0:40
- [x] 1 x # 110-006 - RIGHT SLIDE ENDCAP - 0:21
- [x] 1 x # 115-002 - SIMPLIFIED FOREHEAD BASE SHAPE - 1:11
- [x] 1 x # 130-003 - MODULAR LID MAIN - 2:23
- [x] 1 x # 130-004 - MODULAR MOUNT BLANK - 1:38
- [x] 1 x # 130-005 - LEFT MODULAR CABLE CLAMP - 0:33
- [x] 1 x # 130-006 - RIGHT MODULAR CABLE CLAMP - 0:33
- [x] 1 x # 131-001 - SIMPLIFIED DRIVER BOARD MOUNT - 1:46
- [x] 1 x # 131-002 - SIMPLIFIED DP PORT HOLDER - 0:24

Total Print Time circa **35 hours**

## OPTICS BRACKET Reference Images

Part Number | Design | Print
----------------- | --------- | -------
130-001        |![image](https://user-images.githubusercontent.com/1537834/87444066-3593fa00-c5ee-11ea-8ba7-cc7e6a6203e3.png) | ![image](https://user-images.githubusercontent.com/1537834/87435662-f2348e00-c5e3-11ea-96b4-8c9e352f43d2.png)
111-002        |![image](https://user-images.githubusercontent.com/1537834/87444250-725ff100-c5ee-11ea-866a-a92db47f737e.png) | ![image](https://user-images.githubusercontent.com/1537834/87435729-0a0c1200-c5e4-11ea-9d94-e5c05ad6f80b.png)
112-002        | ![image](https://user-images.githubusercontent.com/1537834/87444344-96233700-c5ee-11ea-8d65-a4cf7ef6c4b3.png) | ![image](https://user-images.githubusercontent.com/1537834/87435759-16906a80-c5e4-11ea-9fd6-fc2a05e37fb4.png)
113-001        | ![image](https://user-images.githubusercontent.com/1537834/87444488-c539a880-c5ee-11ea-893a-b1fc96046a92.png) | ![image](https://user-images.githubusercontent.com/1537834/87435831-26a84a00-c5e4-11ea-853f-54cd7bf2f871.png)
113-002        | ![image](https://user-images.githubusercontent.com/1537834/87444576-de425980-c5ee-11ea-89ae-829bc02656e9.png) | ![image](https://user-images.githubusercontent.com/1537834/87435865-3031b200-c5e4-11ea-84fd-02f930375d6b.png)
110-005        |             | **MISSING - PRINT 110-006**
114-001        | ![image](https://user-images.githubusercontent.com/1537834/87444678-fd40eb80-c5ee-11ea-8787-1e75dcc95e34.png) | ![image](https://user-images.githubusercontent.com/1537834/87435915-3f186480-c5e4-11ea-836c-cf9129128772.png)
114-002        | ![image](https://user-images.githubusercontent.com/1537834/87444761-1b0e5080-c5ef-11ea-9a10-cafb2c5a6e65.png) | ![image](https://user-images.githubusercontent.com/1537834/87435961-4d668080-c5e4-11ea-94f0-c3246d27f275.png)
110-006        | ![image](https://user-images.githubusercontent.com/1537834/87444826-311c1100-c5ef-11ea-9c81-984e8b311223.png) | ![image](https://user-images.githubusercontent.com/1537834/87435982-55bebb80-c5e4-11ea-904f-2cfb9ec0000f.png)
115-002        | ![image](https://user-images.githubusercontent.com/1537834/87444931-514bd000-c5ef-11ea-9df1-6bcebfec29e7.png) | ![image](https://user-images.githubusercontent.com/1537834/87436033-68d18b80-c5e4-11ea-9aeb-60e57d666e02.png)
130-003        | ![image](https://user-images.githubusercontent.com/1537834/87445023-704a6200-c5ef-11ea-8514-f64c2417c386.png) | ![image](https://user-images.githubusercontent.com/1537834/87436056-7129c680-c5e4-11ea-8639-0ce4e9f43a00.png)
130-004        | ![image](https://user-images.githubusercontent.com/1537834/87445094-86f0b900-c5ef-11ea-9af6-4193ade38e11.png) | ![image](https://user-images.githubusercontent.com/1537834/87436085-79820180-c5e4-11ea-81a7-0262e05ca06f.png)
130-005        | ![image](https://user-images.githubusercontent.com/1537834/87445173-9ec83d00-c5ef-11ea-8287-3b0cc3cb078d.png) | ![image](https://user-images.githubusercontent.com/1537834/87436125-869ef080-c5e4-11ea-8975-9ec63fa9c29a.png)
130-006        | ![image](https://user-images.githubusercontent.com/1537834/87445235-b69fc100-c5ef-11ea-9a22-13f5c5d7a3c0.png) | ![image](https://user-images.githubusercontent.com/1537834/87436110-8141a600-c5e4-11ea-8379-2d3bf62a0d1d.png)
131-001        | ![image](https://user-images.githubusercontent.com/1537834/87445336-d800ad00-c5ef-11ea-8a96-b89e88361394.png) | ![image](https://user-images.githubusercontent.com/1537834/87436147-8d2d6800-c5e4-11ea-986a-6554b5c28670.png)
131-002        | ![image](https://user-images.githubusercontent.com/1537834/87445455-f9fa2f80-c5ef-11ea-9785-7c532fa327af.png) | ![image](https://user-images.githubusercontent.com/1537834/87436165-94547600-c5e4-11ea-8400-0208bce805dc.png)

## HEADGEAR 3D Prints:

- [x] 1 x # 210-001 - FOREHEAD MAIN STRUCTURE - 3DPRINT
- [x] 1 x # 210-002 - FOREHEAD HEADGEAR SPAN - 3DPRINT
- [x] 2 x # 210-003 - FOREHEAD HINGE CAP - 3DPRINT
- [x] 2 x # 210-004 - FOREHEAD HINGE BASE - 3DPRINT
- [x] 1 x # 220-001 - REAR HINGE BASE 3DPRINT
- [x] 1 x # 220-002 - REAR HINGE CAP 3DPRINT
- [x] 1 x # 220-001 - REAR HINGE BASE 3DPRINT
- [x] 1 x # 220-002 - REAR HINGE CAP 3DPRINT
- [x] 1 x # 230-001 - LEFT SIDE MAIN SPAN WITH SLIDE BRAKE - 3DPRINT
- [x] 1 x # 230-002 - LEFT BRAKE HOUSING - 3DPRINT
- [x] 1 x # 230-003 - LEFT BRAKE BUTTON - 3DPRINT
- [x] 1 x # 240-002 - RIGHT BRAKE HOUSING - 3DPRINT
- [x] 1 x # 240-003 - RIGHT BRAKE BUTTON - 3DPRINT
- [x] 1 x # 240-001 - RIGHT SIDE MAIN SPAN WITH SLIDE BRAKE - 3DPRINT

## HARDWARE:

- [x] 1  x # 500-001 - [LEFT REFLECTOR](https://www.smart-prototyping.com/Project-North-Star-Lens)
- [x] 1  x # 500-002 - [RIGHT REFLECTOR](https://www.smart-prototyping.com/Project-North-Star-Lens)
- [x] 1  x # 630-001 - [0.304-in OD TORSION SPRING 180 DEG. L-HAND WOUND McMaster # 9271K603](https://www.mcmaster.com/9271k6)
- [x] 1  x # 630-002 - [0.304-in OD TORSION SPRING 180 DEG. R-HAND WOUND McMaster # 9271K668](https://www.mcmaster.com/9271k668)
- [x] 20 x # 640-001 - [M2.5x0.45 6mm LONG STEEL FLAT HEAT SCREW 90 DEG CS McMaster # 91420a016](https://www.mcmaster.com/91420a016)
- [x] 2  x # 640-002 - [M4x0.7 20mm STEEL BUTTON HEAD SOCKET SCREW McMaster # 91239a152](https://www.mcmaster.com/91239a152)
- [x] 34 x # 650-001 - [M2x8mm LONG THREAD-FORMING SCREWS FOR PLASTIC McMaster # 96817a212](https://www.mcmaster.com/96817a212)
- [x] 2  x # 660-001 - [M4x0.7mm ZINC PLATED NYLON INSERT HEX LOCK NUT](https://www.amazon.com/gp/product/B015A3CV5S/ref=oh_aui_detailpage_o00_s00?ie=UTF8&psc=1)
- [x] 2  x # 670-001 - [5/16 ID x 3/4 OD x 1/16in  NEOPRENE WASHER](https://www.amazon.com/s?k=5%2F16+ID+x+3%2F4+OD+x+1%2F16in+NEOPRENE+WASHER&i=industrial&ref=nb_sb_noss)
- [x] 20 x # 690-001 - [M2.5x0.45  3.4mm LONG HEAT-SET INSERT FOR PLASTICS McMaster # 94180a321](https://www.mcmaster.com/94180a321)
- [x] 2  x # 700-002 - [BOE 3.5-in VS035ZSM-NW0 120HZ LTPS 1440*1600 Module](https://www.smart-prototyping.com/Display-for-Project-North-Star-3_5inch-1440x1600-pixels)
- [x] 1  x # 800-001 - [DISPLAY DRIVER BOARD](https://www.smart-prototyping.com/Project-North-Star-Display-Driver-Board)
- [x] 1  x # 900-000 - [eSun 1.75mm PLA Pro (PLA+) 3D Printer Filament Black](https://www.amazon.com/eSUN-1-75mm-Printer-Filament-Colors/dp/B07K642RQP)
- [x] 1  x # 900-001 - [MILLER WELDING GEN. III HEADGEAR](https://store.cyberweld.com/miwehegeiiir.html)
- [x] 2  x # 900-002 - [2mm THICK SELF-STICK ANTI-SKID RUBBER](https://www.amazon.com/gp/product/B01K7JFXAA)
- [x] 1  x # 900-003 - [FOAM HEAD PADDING](https://www.joann.com/airtex-0.5-16-oz.-high-density-foam/2180313.html)
- [x] 1  x # 900-004 - [PADDED CLOTH](https://www.joann.com/headliner-utility-fabric-55-black/3496072.html)
- [x] 2  x # 900-005 - [3x10x165mm 6061 AL. BAR SLIDE   McMaster # 9146t21](https://www.mcmaster.com/9146t21)

**Comment by MatthewCroughan** [comment]
```
Part number     Quantity        Description

OPTICS BRACKET 3D Prints:

- [ ] #130-001        1       SIMPLIFIED OPTICS MAIN BODY - 3DPRINT   
- [ ] #111-002        1       LEFT DISPLAY TRAY - 25cm FOCAL - 3DPRINT        
- [ ] #112-002        1       RIGHT DISPLAY TRAY - 25cm FOCAL - 3DPRINT       
- [ ] #113-001        1       LEFT ROTATION ADJUSTMENT SLIDE MOUNT - 3DPRINT  
- [ ] #113-002        1       LEFT CABLE GUIDE  - 3DPRINT     
- [ ] #110-005        1       LEFT SLIDE ENDCAP - 3DPRINT     
- [ ] #114-001        1       RIGHT ROTATION ADJUSTMENT SLIDE MOUNT - 3D PRINT        
- [ ] #114-002        1       RIGHT CABLE GUIDE - 3DPRINT     
- [ ] #110-006        1       RIGHT SLIDE ENDCAP - 3DPRINT    
- [ ] #115-002        1       SIMPLIFIED FOREHEAD BASE SHAPE - 3DPRINT        
- [ ] #130-003        1       MODULAR LID MAIN - 3DPRINT      
- [ ] #130-004        1       MODULAR MOUNT BLANK - 3DPRINT   
- [ ] #130-005        1       LEFT MODULAR CABLE CLAMP - 3DPRINT      
- [ ] #130-006        1       RIGHT MODULAR CABLE CLAMP - 3DPRINT     
- [ ] #131-001        1       SIMPLIFIED DRIVER BOARD MOUNT - 3DPRINT 
- [ ] #131-002        1       SIMPLIFIED DP PORT HOLDER - 3DPRINT     

       
HEADGEAR 3D Prints:

- [ ] #210-001        1       FOREHEAD MAIN STRUCTURE - 3DPRINT       
- [ ] #210-002        1       FOREHEAD HEADGEAR SPAN - 3DPRINT        
- [ ] #210-003        2       FOREHEAD HINGE CAP - 3DPRINT    
- [ ] #210-004        2       FOREHEAD HINGE BASE - 3DPRINT   
- [ ] #220-001        1       REAR HINGE BASE 3DPRINT 
- [ ] #220-002        1       REAR HINGE CAP 3DPRINT  
- [ ] #220-001        1       REAR HINGE BASE 3DPRINT 
- [ ] #220-002        1       REAR HINGE CAP 3DPRINT  
- [ ] #230-001        1       LEFT SIDE MAIN SPAN WITH SLIDE BRAKE - 3DPRINT  
- [ ] #230-002        1       LEFT BRAKE HOUSING - 3DPRINT    
- [ ] #230-003        1       LEFT BRAKE BUTTON - 3DPRINT     
- [ ] #240-002        1       RIGHT BRAKE HOUSING - 3DPRINT   
- [ ] #240-003        1       RIGHT BRAKE BUTTON - 3DPRINT    
- [ ] #240-001        1       RIGHT SIDE MAIN SPAN WITH SLIDE BRAKE - 3DPRINT 

HARDWARE:       Quantity        Description     Source:

- [ ] #500-001        1       LEFT REFLECTOR  https://www.smart-prototyping.com/Project-North-Star-Lens
- [ ] #500-002        1       RIGHT REFLECTOR https://www.smart-prototyping.com/Project-North-Star-Lens
- [ ] #630-001        1       0.304-in OD TORSION SPRING 180 DEG. L-HAND WOUND        McMaster #9271K603, https://www.mcmaster.com/9271k6
- [ ] #630-002        1       0.304-in OD TORSION SPRING 180 DEG. R-HAND WOUND        McMaster #9271K668, https://www.mcmaster.com/9271k668
- [ ] #640-001        20      M2.5x0.45 6mm LONG STEEL FLAT HEAT SCREW 90 DEG CS      McMaster #91420a016, https://www.mcmaster.com/91420a016
- [ ] #640-002        2       M4x0.7 20mm STEEL BUTTON HEAD SOCKET SCREW      McMaster #91239a152, https://www.mcmaster.com/91239a152
- [ ] #650-001        34      M2x8mm LONG THREAD-FORMING SCREWS FOR PLASTIC   McMaster #96817a212, https://www.mcmaster.com/96817a212
- [ ] #660-001        2       M4x0.7mm ZINC PLATED NYLON INSERT HEX LOCK NUT  https://www.amazon.com/gp/product/B015A3CV5S/ref=oh_aui_detailpage_o00_s00?ie=UTF8&psc=1
- [ ] #670-001        2       5/16 ID x 3/4 OD x 1/16in  NEOPRENE WASHER      https://www.amazon.com/s?k=5%2F16+ID+x+3%2F4+OD+x+1%2F16in+NEOPRENE+WASHER&i=industrial&ref=nb_sb_noss
- [ ] #690-001        20      M2.5x0.45  3.4mm LONG HEAT-SET INSERT FOR PLASTICS      McMaster #94180a321, https://www.mcmaster.com/94180a321
- [ ] #700-002        2       BOE 3.5-in VS035ZSM-NW0 120HZ LTPS 1440*1600 Module     https://www.smart-prototyping.com/Display-for-Project-North-Star-3_5inch-1440x1600-pixels
- [ ] #800-001        1       DISPLAY DRIVER BOARD    https://www.smart-prototyping.com/Project-North-Star-Display-Driver-Board
- [ ] #900-000        1       eSun 1.75mm PLA Pro (PLA+) 3D Printer Filament Black    https://www.amazon.com/eSUN-1-75mm-Printer-Filament-Colors/dp/B07K642RQP        
- [ ] #900-001        1       MILLER WELDING GEN. III HEADGEAR        https://store.cyberweld.com/miwehegeiiir.html
- [ ] #900-002        2       2mm THICK SELF-STICK ANTI-SKID RUBBER   https://www.amazon.com/gp/product/B01K7JFXAA
- [ ] #900-003        1       FOAM HEAD PADDING       https://www.joann.com/airtex-0.5-16-oz.-high-density-foam/2180313.html#start=1
- [ ] #900-004        1       PADDED CLOTH    https://www.joann.com/headliner-utility-fabric-55-black/3496072.html
- [ ] #900-005        2       3x10x165mm 6061 AL. BAR SLIDE   McMaster #9146t21, https://www.mcmaster.com/9146t21

```

**Comment by ajlennon** [comment]
Opened an issue on the missing STL file

https://github.com/leapmotion/ProjectNorthStar/issues/42

**Comment by MatthewCroughan** [comment]
Build was successful on September 9th 2020. I made the following tweet afterwards
https://twitter.com/MatthewCroughan/status/1303773226301095936

![image](https://user-images.githubusercontent.com/26458780/93710658-532a9600-fb40-11ea-9339-4b538efd5516.png)

# Still Todo

- [ ] Calibrate headset

@goatchurchprime needs to make a scene in the Godot game engine that is capable of helping us tune the headset.


- [ ] Get 6DoF working

We do not have the [intel realsense t265 ](https://www.intelrealsense.com/tracking-camera-t265/) camera that would otherwise give us 6DoF and hand tracking capabilities at the moment. However, @goatchurchprime has suggested that a vive tracker will suffice. We can print an alternative mount for the headpiece that will support this vive tracker.

**Comment by ajlennon** [comment]
So we've had luck getting the display output on the existing build.

We bought the bits for the 6dof support and in the process decided to upgrade to the more recent mechanical build which is called Deck X. This involved 3D printing new parts so I am going to put down what I'm going to do for these below

**Comment by ajlennon** [comment]
3D Parts from the [ProjectNorthStar](https://github.com/CombineReality/ProjectNorthStar/tree/master/Mechanical/CombineReality_Variants/Deck_X) DeckX.

Trying to order these in order of assembly documents [here](https://project-north-star.gitbook.io/project-north-star/mechanical/combine-reality-deck-x/deck-x-assembly-guide)

- [x] DeckX_Optics_Bracket.stl (20 hours)
- [x] DeckX_Leap_Motion_Spacer.stl (51 minutes)
- [x] 25cm_Tray.stl (4 hours 38 minutes) (needed to print this with a skirt as it was lifting and deforming - **got a probem with support on this bonding too tightly to the shape to be removed?)
- [x] 25cm_Tray.stl (4 hours 38 minutes) (mirrored ???)
- [x] DeckX_Sensor_Bracket.stl (2 hours 5 mins)
- [ x DeckX_Lid.stl (14 hours)
- [x] DeckX_D-Pad.stl (25 minutes)
- [x] DeckX_Circle_Button.stl (12 minutes) (needs brim)
- [x] DeckX_Dot_Button.stl (12 minutes)
- [x] DeckX_Facial_Interface.stl (52 minutes)
---
- [ ] 75cm_Tray.stl (N/A - using 25cm trays for now)
---

Part Name                     | Design | Print
------------------------------- | --------- | -------
DeckX_Optics_Bracket | ![image](https://user-images.githubusercontent.com/1537834/99150063-e50ad700-2689-11eb-9781-2a3b4ca14a3b.png)| ![image](https://user-images.githubusercontent.com/1537834/99150097-15527580-268a-11eb-9cf2-fef1dcb0580b.png)
DeckX_Leap_Motion_Spacer | ![image](https://user-images.githubusercontent.com/1537834/99150249-04563400-268b-11eb-9ffb-49ea20534d74.png) | ![image](https://user-images.githubusercontent.com/1537834/99156710-00daa100-26bb-11eb-9c11-1c0e79be8167.png)
25cm_Tray | ![image](https://user-images.githubusercontent.com/1537834/99150271-2fd91e80-268b-11eb-9e17-4a5d53c055b2.png) | ![image](https://user-images.githubusercontent.com/1537834/99154017-71c28e80-26a4-11eb-9aa9-cec7329705d1.png)
25cm_Tray (mirrored) | TBD | 
Lid | ![image](https://user-images.githubusercontent.com/1537834/99150357-efc66b80-268b-11eb-885d-c3e35e0e7038.png) | ![image](https://user-images.githubusercontent.com/1537834/99783770-c6399400-2b12-11eb-9c78-5b4ceb0fdd84.png)
DeckX_Sensor_Bracket | ![image](https://user-images.githubusercontent.com/1537834/99150625-c8709e00-268d-11eb-88aa-768b2ce53c0f.png) | ![image](https://user-images.githubusercontent.com/1537834/99150650-e9d18a00-268d-11eb-94d0-ff735f3506d1.png)
DeckX_D-Pad | ![image](https://user-images.githubusercontent.com/1537834/99150502-f5708100-268c-11eb-917f-eef458893aaa.png) | ![image](https://user-images.githubusercontent.com/1537834/99155397-822c3680-26af-11eb-97a3-87a091057c5f.png)
DeckX_Circle_Button | ![image](https://user-images.githubusercontent.com/1537834/99150556-58faae80-268d-11eb-9e91-68975307b2ef.png) | ![image](https://user-images.githubusercontent.com/1537834/99154749-fbc12600-26a9-11eb-98fb-8b72bbe275cc.png)
DeckX_Dot_Button | ![image](https://user-images.githubusercontent.com/1537834/99150582-8d6e6a80-268d-11eb-97a2-383631672628.png) | ![image](https://user-images.githubusercontent.com/1537834/99154893-3d9e9c00-26ab-11eb-91ce-e0ec0780b761.png)
DeckX_Facial_Interface | ![image](https://user-images.githubusercontent.com/1537834/99150974-e0492180-268f-11eb-81bc-fc408abc7283.png) | ![image](https://user-images.githubusercontent.com/1537834/99158216-5d908880-26c8-11eb-82ff-2f57ca3de53a.png)

**Comment by ajlennon** [comment]
**Calibration Stand Assembly** as per [this](https://project-north-star.gitbook.io/project-north-star/mechanical/calibration-stand-assembly-guide) and [this](https://project-north-star.gitbook.io/project-north-star/calibration/getting-started)

The right link for these source files is [here](https://github.com/CombineReality/ProjectNorthStar/blob/master/Mechanical/3D%20Prints.zip). Extract and use "Calibration Stand" files, FDM optimised.

We also need a custom model for the T261 mount instead of the ELP camera. This is currently found on the Northstar Discord server [here](https://cdn.discordapp.com/attachments/525569179944747028/758147008279871488/t261_mount.obj)

| Done | Code        | Number | Name | Print Time |
| ------- | ------------- | ----------- | -------- | -------------- |
| [x] | #310-001 | 1            | BASE MOUNTING PLATE | 9 hours |
| [x] | #310-002 | 1            | LEFT LEFT STAND | 6 hours |
| [x] | #310-003 | 1            | RIGHT LEFT STAND | 6 hours |
| [x] | #320-001 | 1            | DUAL STEREO CAMERA MOUNT BRACKET | 1 hour 38 mins |
| [x] | #320-002 | 2            | STEREO CAMERA STIFFENER | 1 hour 25 mins |
| [x] | #320-003 | 1            | CAMERA CROSSBEAM | 4 hours 18 minutes |
| [x] | ? | 1            | T261 mount | 1 hour 16 mins |

Also need to buy these parts from the [BOM](https://project-north-star.gitbook.io/project-north-star/calibration/getting-started/calibration-stand-bom)

| Done | Code        | Number | Description | Source |
| ------- |  ------------  | ----------- | --------------- | --------- | 
| [ ] | #640-001 | 8 | M2.5x0.45 6mm | LONG STEEL FLAT HEAT SCREW 90 DEG CS | McMaster #91420a016
| [ ] | #650-001 | 22 | M2x8mm LONG THREAD-FORMING SCREWS FOR PLASTIC | McMaster #96817a212
| [ ] | #690-001 | 8 | M2.5x0.45 3.4mm LONG HEAT-SET INSERT FOR PLASTICS | McMaster #94180a321 
| [ ] | #700-003 | 2 | ELP USB CAMERA MODULE DUAL LENS STEREO (Use T261 instead???) | Amazon

| Name | Model Image | Print Image |
| -------- | ----------------- | ---------------- |
| T261 mount | ![image](https://user-images.githubusercontent.com/1537834/99876904-01f75b00-2bf2-11eb-9935-b4c8015eaffc.png) | ![image](https://user-images.githubusercontent.com/1537834/99876939-471b8d00-2bf2-11eb-8481-7ddb51929420.png) |
| BASE MOUNTING PLATE | ![image](https://user-images.githubusercontent.com/1537834/99877094-a6c66800-2bf3-11eb-8d0d-3db6a25b97d8.png) | ![image](https://user-images.githubusercontent.com/1537834/99887911-3db91180-2c40-11eb-83f0-435e2bd1b93e.png) |
| LEFT LEFT STAND | ![image](https://user-images.githubusercontent.com/1537834/99877271-b8f4d600-2bf4-11eb-91e6-333bc1da9775.png) | ![image](https://user-images.githubusercontent.com/1537834/99900983-22cfb700-2cab-11eb-828c-25eaa71813eb.png)
| RIGHT LEFT STAND | ![image](https://user-images.githubusercontent.com/1537834/99878532-01fd5800-2bfe-11eb-841b-2726a31cf132.png) | ![image](https://user-images.githubusercontent.com/1537834/99900978-1a777c00-2cab-11eb-920d-f42a357ad581.png)
| DUAL STEREO CAMERA MOUNT BRACKET | ![image](https://user-images.githubusercontent.com/1537834/99901016-6c200680-2cab-11eb-969d-1614b5aacbc5.png) | ![image](https://user-images.githubusercontent.com/1537834/99907641-df3e7280-2cd5-11eb-8951-edb5c16918f5.png) |
| STEREO CAMERA STIFFENER | ![image](https://user-images.githubusercontent.com/1537834/99901713-aa6bf480-2cb0-11eb-82f8-673024673fe6.png) | ![image](https://user-images.githubusercontent.com/1537834/99907627-cafa7580-2cd5-11eb-81df-81ee2f10660b.png) |
| CAMERA CROSSBEAM | ![image](https://user-images.githubusercontent.com/1537834/99901745-ec953600-2cb0-11eb-9d17-6b1f7fb78699.png) | ![image](https://user-images.githubusercontent.com/1537834/99915029-11150080-2cf9-11eb-921d-dc04336df4ea.png) |

**Comment by MatthewCroughan** [comment]
@goatchurchprime Shall we mark this as complete since we did build and attempt to calibrate/use this, and it is sitting in a box near to your desk now.
