### ISSUE TITLE
Get the electrician to complete his tasks

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#1507]
We are building up a list of things that the electrician needs to do so I wanted to have a single place to find them:

Urgent:
* [ ] Place a visible alarm in the CNC room #1050
* [x] Socket in the kitchen isn't working #1739
* [x] Socket in the laser room isn't working #1829 
* [x] Fan in the more accessible toilet isn't working #1777 
* [x] Light switch in the less accessible toilet isn't working #1763 

Less urgent:
* [ ] Replace the lights in Room 29 #997
* [x] Light in the nook not working #1830 
* [ ] Fit a separate fuse box for meters for the air conditioner circuits
* [x] Replace the B32 circuit breaker with a C-type one for the main room east-side circuit.
* [x] ~Replace the water heater in the kitchen #1425 (maybe this should be done by a plumber?!)~

**Comment by johnmckerrell** [comment]
Updated the description to mention that we're getting a plumber to do the water heater and also replacing a circuit breaker.

**Comment by johnmckerrell** [comment]
And now I've remembered another thing we wanted him to do which was add a separate fuse box that can contain circuit breaker sized meters. We were going to put one on the air conditioning originally and see what we thought before fitting more on the other air conditioner circuits. As this isn't required for the space I'll just leave it here as a comment for now.

**Comment by magman2112** [comment]
I'm not sure if this has been commented on much before, but the lighting in the laser room is not really sufficient for a workshop. I believe that the same light unit is used in the Wood Workshop/ CNC Room. which is considerably smaller. 

The lighting in Dinky is also not so good, but this can be supplemented by task lighting if required, which is not really appropriate in the laser room

Perhaps we can enquire about improving the lighting in the laser room, along with the rest of the work we are asking the electrician to look at.

**Comment by johnmckerrell** [comment]
We can but he works better with suggestions so if you have an idea of what we should get in there please say!

**Comment by johnmckerrell** [comment]
Electrician will be in on Wednesday, should do the breaker and the sounder at least. I'll try to discuss the lighting with him.

I guess one problem with the laser room is that we don't know what the layout will be yet?

**Comment by magman2112** [comment]
I was discussing the laser room layout with @Sean-anotherone on Thursday and I suspect the layout will likely stay pretty much as it is now. We could reorient Gerald, but this would make access for mirror alignment more difficult, so I suspect that Gerald will have to stay in the same place.

In terms of lighting improvements, I suspect a more empirical view may help. With the current lighting at night it is difficult to read a printed page when placed on Gerald, virtually directly below the one light in the room. We should move to a lighting setup where we can read printed documents placed on all of the machines. 

There are workplace standards for light levels which give recommendations for light levels in various work environments, here’s a quick table from the USDAW website 

https://www.usdaw.org.uk/USDAW/media/Documents/Health%20and%20Safety/Health%20and%20Safety%20A-Z/Workplace-Lighting.pdf

If we could get access to a lux meter, we should be able to measure the light levels we have at the moment then work towards an optimum solution for this space. I would suggest that a light level of at least 100 lux, possibly 200 lux is needed in the laser room.

This standard may also come in useful for other spaces in DoES as well, depending on the tasks undertaken in the spaces.

You can also access the full HSE guide on lighting at work at the following location.

https://www.hse.gov.uk/pUbns/priced/hsg38.pdf

**Comment by johnmckerrell** [comment]
Mick has been in, he's suggested that in Room 29 we could have 4 drop pendant lights on either side, they would be on long flexes leading from the existing central fittings and hanging over hooks in the ceiling. A benefit of this solution would be that if we moved the desks in the future we could easily move the lights around by just moving the hooks in the ceiling, no electrical work needed. Also they would be standard pendants with replaceable bulbs.

He can do it today so any feedback anyone has would be good if they thought this would be a terrible idea. We can't change how it's switched so the only option not have all lights on at once would be to have a pull cord on the central rose to allow either side of the room to be turned off. Or Wi-Fi bulbs of course but we would need to provide those!

**Comment by amcewen** [comment]
That sounds like a pretty decent upgrade (8 lights in total, right?)  I don't suppose he's shared details of what the shades look like, or would they be something we can provide/change?

**Comment by johnmckerrell** [comment]
Yes 8 lights. No, we have no details yet, I did mention that flex and pendant should really be dark coloured.

**Comment by magman2112** [comment]
This sounds like a good idea, especially if we add dimmers, or possibly Phillips Hue bulbs or an equivalent.

The only issue I have thought of is possible reflections off the TV screen, when FindOut Digital are using the room post COVID, so it might be worth contacting Ben in case he isn’t on GitHub or WhatsApp.

I suspect we can mitigate this though with shades for the pendants, we could even make some of our own shades if we want to.

**Comment by johnmckerrell** [comment]
Electrician has suggested this one fitted for £150. I'm not sure on the brass fittings and it had 5 pendants which is one too many technically. We could always look around for a different one though (not sure how much of the cost is fitting at this point).


![IMG_7703](https://user-images.githubusercontent.com/27243/100883735-955d4580-34a8-11eb-8766-83bae454886b.jpg)

The new optical "sounder" is on order, should arrive tomorrow.

To fit a new consumer unit for meters and fit the meters will cost £80, I've said we'll go ahead with that so @goatchurchprime can you order 3 more meters?

He recommended a LED "tube" suspended from the ceiling for the laser room. Any thoughts?

**Comment by johnmckerrell** [comment]
@magman2112 actually this wasn't suggested for Dinky but could also be a reasonable option, yes Wi-Fi bulbs could be useful and also making our own shades

**Comment by magman2112** [comment]
Sorry, getting the rooms mixed up.

For the laser room, I don’t know how bright a single tube would be, especially at the ends of the room. 

I think we should be aiming for reasonable illumination from the Middle of Tony and to the end of Sophia near the door (when all the lasers are back in this room). I suspect 2 tubes might be better, but this may be an issue due to the girder in the roof towards the door.

**Comment by Sean-anotherone** [comment]
Related but not directly connected to this, a desk light that can be used during maintenance work in laser room would be great too - the one from the electronics bench does work, but is large and clunky and often in use.
Sean

    On Wednesday, 2 December 2020, 12:53:17 GMT, John McKerrell <notifications@github.com> wrote:  
 
 


Yes 8 lights. No, we have no details yet, I did mention that flex and pendant should really be dark coloured.
