### ISSUE TITLE
Create a "Cost of Being Epic" poster for the space (and online)

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#24]
It would be useful to help people understand how DoES is funded, what its costs are, and how they can help with that.

Other hackspaces, etc. often have a "Cost of Hacking" poster, that shows income/outgoings, and what people can do to help - for example (although it's an online version) see https://london.hackspace.org.uk/cost-of-hacking/

The (current) figures for DoES are in http://doesliverpool.com/business/building-a-self-sustaining-community-space/ which also gives some thoughts on how to help.

If someone designs the posters, there's budget to get them properly printed somewhere, so we can do something ~A2 size (bigger than A4 definitely), and then put them up in each of the rooms at the space.

Ideally the design would be one that's easy to update, as we'll need to reprint them when the numbers change significantly (as the income is going to be the most volatile, I wonder if there's any easy way to make that particular number simple to change?)

**Comment by amcewen** [comment]
Change the "Make a Donation" to "Become a Friend", add something about the workshop, update the numbers (talk to @johnmckerrell for that, probably), and add a URL for a call to action - doesliverpool.com/help

**Comment by aubergine10** [comment]
There's been no direct activity on this issue for over 2 years - I've labelled it as "stale?" and will close it in a month if no further updates.

Tip: You can remove "stale?" label to prevent this ticket being closed.

**Comment by amcewen** [comment]
I'd still like us to have this as I think it would be good for us to be more up-front(/visible) about the costs of running DoES.  I had been wondering about asking Steve H if he'd be up for having a crack at it, but he left just around then :-/

Maybe we need to more actively look for a dataviz person?

**Comment by aubergine10** [comment]
I agree that there needs to be transparency/realism over the costs - is this something that could be automated? If we can get the data from accounts package (does FreeAgent have suitable API?) then we could potentially pump that in to a web page - it doesn't need to be super-pretty to start with; future iterations can deal with that. I'd very much like to see a dashboard on a wall somewhere that shows the health metrics of DoES.

**Comment by amcewen** [comment]
Organisers' meeting notes: @huffeec to chase up with Kate to see if she can run at this.

**Comment by johnmckerrell** [comment]
I also pointed @Red-Violet at this recently

**Comment by DoESsean** [comment]
With the move, our costs are going to go up, which means that this is more important than ever.

@huffeec, did you have any luck with Kate?

**Comment by amcewen** [comment]
Kate has produced one, and it's stalled with me getting back to her on it.  I'll dig out the email and chase things up.

**Comment by huffeec** [comment]
I've spoken to her again and she's happy to do more on this. Trying to convince her to come on Saturday too.

**Comment by DoESsean** [comment]
Did you get in touch with Kate, @amcewen?

**Comment by DoESsean** [comment]
Just came to say that this is now SUPER important, and noticed that there is currently an action outstanding.

@amcewen is there any movement on this?

**Comment by DoESsean** [comment]
Have just spoken to @amcewen about this, and it's been suggested that I liaise with Kate directly.

I think it is worth, either as a stop gap or even as the final design, getting something put together that at least shows how much the space costs to run each month (taking an average since we moved in, maybe discounting the expenses such as carpets and blinds, which would be classed as moving costs, maybe not) and how that is funded - ie, 100% community, 0% outside funding.

**Comment by johnmckerrell** [comment]
Might use the financials report as a source of data. https://github.com/DoESLiverpool/somebody-should/wiki/Financials201901

**Comment by johnmckerrell** [comment]
It would be good to have at least a version of this ready for GovJam on the 23rd.

**Comment by amcewen** [comment]
@zarino and I have been chipping away at this.  Generating it all in SVG is a pain because SVG doesn't do text very well, so we're looking at SVG for the chart and then HTML for the remainder.

We want a version that can be printed (at A2 or A1? size) and also go on the website, so generating a print version is the main stumbling block right now.

[weasyprint](https://weasyprint.org/start/) looks promising, or [xhtml2pdf](https://github.com/xhtml2pdf/xhtml2pdf) might if that doesn't do the job.

**Comment by amcewen** [comment]
Now that we've got clip frames to hold these (see #1644), @Robotorium and I picking away at this again.  It'll be printed at A1 size, and need to be portrait orientation.

This is the [terrible first draft SVG - CostOfBeingEpic.svg](https://user-images.githubusercontent.com/108468/154806162-9d470834-396f-42d7-8655-92746b415d65.svg) that I've got some code to auto-generate.  The graph itself maybe isn't too bad — could do with better colours, but it's the surrounding text, etc. that needs most work (and possibly not to be in an SVG?)

**Comment by amcewen** [comment]
Having gotten the `financial-report` code up and running properly on my machine today, I think extending @johnmckerrell's existing reports will be a better way to generate the poster.

I've [opened an issue over there to track it](https://github.com/DoESLiverpool/financial-report/issues/30)

**Comment by amcewen** [comment]
Just a note to point to the [update on progress](https://github.com/DoESLiverpool/financial-report/issues/30#issuecomment-2577331353) that I posted over on the `financial-report` issue.

**Comment by amcewen** [comment]
I think I'm getting close to something usable for this.  It currently looks like this:

![Image](https://github.com/user-attachments/assets/f7e4c02e-ec5e-45da-8902-0650d9592867)

As [I noted on the `financial-report` issue](https://github.com/DoESLiverpool/financial-report/issues/30#issuecomment-2781337240) the remaining tasks (I think) are:
* [x] replace the "Rates and Risk of Closing" paragraph with something current about our finances
* [ ] create the doesliverpool.com/help page - I've spun that out as #2032
* [x] (maybe further tune the colours)
* [x] print it out and put it up

**Comment by amcewen** [comment]
I got this finished off and printed out today:

![Image](https://github.com/user-attachments/assets/64ee2216-b01a-4202-b036-f55474c1c98e)

Still to do:
* [x] The help page, as detailed in #2032.
* [x] Putting it online somewhere.  On the `/help` page maybe??
* [x] Putting a version up in the main room.  I've printed out two copies (though one has a muddier red and imperfect spacing, but I think is good enough) and they're *both* in the clip frame in the Events Room.  I think we need to get another clip frame for the one in the main room (it's not the frame by @Robotorium's desk, that's too small and was the one for the newspaper article)

**Comment by amcewen** [comment]
I've ordered another [A1 clip frame](https://www.ukpos.com/black-snap-frame-25mm-frame) (the same as the existing ones) and when that arrives we can mount it in the kitchen next to the DoES Values that @hotcuppa and I put up today (#1644)

**Comment by amcewen** [comment]
The clip frame has arrived.  I've left it propped up against the wall next to where it needs to be mounted (@hotcuppa and I marked the location for the top-right screw on the tape on the wall on Sunday)

**Comment by amcewen** [comment]
I've updated the posters for the six months to the end of October.  We're making less of a loss than we were that time, but still losing ~£240/month 😞  So we need to bring more folk in to the space!

I've also published the newer version on the website at https://doesliverpool.com/cost-of-doing-epic/ (as a page of its own, as I think that'll make it easier to cut-and-paste the generated poster in future versions).

There's still a clip-frame in the kitchen that needs to be mounted on the wall, and when it does the DoES Values poster can be pulled out from behind the Cost of Doing Epic poster so we've got both of those on display.  I figured the Cost of Doing Epic was the more important one to have on show while we wait for someone to drill a few holes.

**Comment by hotcuppa** [comment]
The signs are now up in the kitchen. Issue closed!
