### ISSUE TITLE
do a major service on sophia

### ISSUE THREAD

**Issue by DefProc** [DoESLiverpool/somebody-should#605]
Sophia has been collecting enough fixes, and has enough worn parts that it's worth taking it out of service for a week or more to perform a major service and get our small cutter running more reliably again.

We'll need to collate a list so there's a clear idea of all the things than need doing as part of a service, where appropriate, these should link back to an issue (open or closed):

 - [x] Replace Sophia's carriage drive belt #565
 - [x] Sophia needs new wheels #198 
 - [x] Deep clean or replace Sophia's lens after checking #493
 - [ ] Report any instances of Sophia slipping #505
 - [x] One of the internal fans in Sophia isn't operating #525
 - [ ] Sophia needs a new focus ruler #191
 - [x] Clean down the whole inside of cutting residue
 - [ ] Any more?

It's already looks like a big job, and some of these require more than one person. It would be great to get a working group together from the wider community. Can you help with this service?

**Comment by de14n** [comment]
I can help out if needed. (I might come across as dim, but I'm incredibly hands on, I've worked on many types of industrial machinery, from lathes to cnc millers (bridgeport) to extrusion lines (IDE), injection molders (Arburg) and semi-autonomous work jigs. I'm trained to maintain high standards on production lines and I methodically troubleshoot problems to prevent expensive downtime, so this should be doable.)

I guess it will be good days work for two to three people, and we'd need the space (like on the desk in Dinky?). Do we have/require any specialist tools?

**Comment by ajlennon** [comment]
The exhaust hose is knackered and possibly needs to be replaced

**Comment by huffeec** [comment]
The exhaust is knackered beyond usable now, it's not possible to get out of the window. I'll measure it on Saturday so we can order a replacement.

**Comment by cheapjack** [comment]
Think I did a quick fix getting something from toolstation but obviously needs measurement. ONly suggest toolstation as they are open from 7am on a Saturday and are cheap...

https://www.toolstation.com/shop/Electrical/d190/Ducting/sd3083/PVC+Flexible+Ducting+Hose/p32740

**Comment by DefProc** [comment]
It is a 100mm (4 inch) hose from Sophia. 

The aluminium was chosen last time as fire is possible in the ducting from the inevitable buildup of post laser soot. The ideal would be straight sided aluminium ducting, but that's more likely to be useful for a fixed installation.

**Comment by johnmckerrell** [comment]
Was anything ordered for this? It really is knackered, we managed to find a section in the cupboard and taped it together but it's really not great.

**Comment by DoESsean** [comment]
The photo recently posted on Twitter was by me - Dominic from Smoke and Mirrors had popped in to have a look and needed to know what size the space I posted was so that he knew what we needed.

**Comment by Dowz77** [comment]
I'll post some updates on here to document maintenance done so we have a record

HV power supply proved to be working #676 and removed for cleaning

![psu1](https://user-images.githubusercontent.com/36996732/39120354-1dba6790-46e6-11e8-888b-36ed70367b1e.png)

![psu](https://user-images.githubusercontent.com/36996732/39120378-28e5bd18-46e6-11e8-8a0c-85dbaaf254b7.png)

**Comment by Dowz77** [comment]
Cutting bed cleaned

![bed](https://user-images.githubusercontent.com/36996732/39120651-eeb037b2-46e6-11e8-9d91-e6f0d0e22545.png)

**Comment by johnmckerrell** [comment]
Any idea when we expect Sophia to be operational? I don't think anyone's pulled the trigger on getting new optics yet although it seemed like we'd mostly decided what was needed.

**Comment by Dowz77** [comment]
It requires the optics and a new tube. I'll refit above parts, new fan if it's found and fit the water connection that has arrived this week, probably maker night. If the optics and tube can be sourced for then it could be back in action Thursday.

**Comment by jackie1050** [comment]
There is a tube in a cardboard box in front of Sophia - is this the replacement tube and is it waiting to be fitted? @johncain39 will arrange a time to fit it oif that's what needs doing

**Comment by johnmckerrell** [comment]
https://github.com/DoESLiverpool/somebody-should/issues/676#issuecomment-387391900 suggests it is.

@Dowz77 any chance you can update the checkboxes on this issue and perhaps have a scan through the other Sophia issues as I suspect you can clear out a fair few, you can find the others here:

https://github.com/DoESLiverpool/somebody-should/labels/Tool%3A%20Laser%20Cutter%20-%20Small%20%28Sophia%29

**Comment by magman2112** [comment]
A new laser tube and Lens were fitted to Sophia on Tuesday 15th May. 

With @johnmckerrell we got Sophia plumbed in and the extractor working, but we noticed that we were getting very poor cuts on the y-axis on a test cut and the y-axis often jammed. 

looking at the traveling head on the y-axis showed a lot of play on the wheels with the left rear wheel in particular dropping out of position. It would appear that it may be preferable to use V-wheels rather than than the square edge nylon wheels that are currently fitted to Sophia.

With a little digging, I found some Open Build mini-wheels which may be a good fit, so I ordered 4 from Robocutters:
https://www.robocutters.co.uk/proddetail.asp?prod=V_SlotMiniVWheelKit&cat=21

Once they are delivered, we can try them for size, though we may need to modify the mounting plate, as these wheels use an M5 bolt, rather than what are apparently M3 on the current wheels.

**Comment by magman2112** [comment]
I found a suitable replacement fan in the Laser Spares cupboard, so I fitted this today. Whilst fitting this, I noticed that the mains cables for the fans went through an un-insulated hole in the hole in the metal chassis, which is unsafe. I drilled a larger hole and fitted a grommet that @amcewen had, then re-fitted the mains connections for the fans.

Both fans are now working correctly.

**Comment by DoESsean** [comment]
This is basically happening all the time. It does mean, however, that once Sophia is up and running after each overhaul, the issue should be closed and a new one opened for any new problems that arise, otherwise it can be easy for things to get lost.

With that in mind, I'm closing this issue, although am happy for it to be reopened if it's felt necessary.
