### ISSUE TITLE
Make Dinky a nice space for meetings

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#961]
Dinky is seeing more use now (and Find Out will be starting to use it even more now that their UX lab fit-out is done).

It's a bit echoey at present, and has a semi-random collection of desks in there.  We should make it look nice.

We haven't done anything with the floor in there, should we carpet it?  That would help with the acoustics.  Should we get some plants?  At one point we'd suggested putting the big table that used to be in the middle of the main room in Gostins in there - do we still want to do that (it needs a bit of repair to the support, as that got damaged in the move).

Things to do for it:
 * [x] Carpet
 * [x] Cover the breezeblock former-doorway
 * [x] Install some whiteboards
 * [ ] Cover the breezeblocks under the window
 * [x] Get some heating (covered in #1277)
 * [x] Finish sanding and oil/seal the big table (covered in #1020)
 * [x] Fit blinds on the window (covered in #849)
 * [ ] Fit cover plate over the networking socket high on the main-room side wall
 * [ ] Plaster and paint the bit of wall under the sockets on the UX-lab side wall

**Comment by johnmckerrell** [comment]
There's a previous issue for carpet in here - https://github.com/DoESLiverpool/somebody-should/issues/709

 I think Find Out would want to be very involved in how this room is laid out, to the extent that they'd potentially want to have a veto on some of the choices (or at least may have a strong opinion).

A new hole has opened as one of the floorboards has flaked apart, that may or may not need fixing before getting some carpet in.

**Comment by johnmckerrell** [comment]
I've requested an updated quote from Bogans.

**Comment by amcewen** [comment]
Planning to...
 * Move everything out of the room
 * Sort out the big table from Gostins to put in the centre
 * Get a matching set of decent chairs from the events room
 * Get it carpetted
 * Sort out something for the breeze block wall under the window
 * Get a storage cupboard to go in front of the breeze block doorway on the wall

We should also work out which furniture we should get rid of, rather than just moving stuff into storage somewhere.

**Comment by johnmckerrell** [comment]
Breeze-block wall under the window is 3150x1030mm. I'm looking at getting panels that are 250mm x 2.6m. So we need 13 strips that are 1030mm long. 1 Pack will give 8 full strips and 4 part-strips so we should need two packets (which should give us 16 full strips and be plenty to do the job).

https://www.ebay.co.uk/itm/Rustic-Brick-Red-Bathroom-Wall-Panels-Cladding-Shower-PVC-Waterproof-Pk-of-4/132825439828?epid=16024936151&hash=item1eed035e54:g:Ft8AAOSwhntbyb7c:rk:8:pf:0

**Comment by johnmckerrell** [comment]
After discussions elsewhere we're thinking it might be better to just go for plasterboard & paint. I found a few options[1], I don't know how you would fit them but something you can "just" cut to size and affix to the wall easily seems like a good option. I think with these sizes you'd probably just have a single join to tape and seal, then a lick of paint and you're sorted!

1 - https://www.insulation4less.co.uk/plasterboard-systems/insulated-plasterboard/0_020_w_mk/

Regarding heating, I mentioned it to Mick and he just said a wall mounted convection heater would be the obvious thing. It wouldn't be high load so you could just plug it into the wall. As such it should be quite feasible for us to do it. He did talk about putting a heater under the table, I'm checking with him what he had in mind for this.

**Comment by johnmckerrell** [comment]
Yeah Mick just says he meant a fan heater. Screwfix have various panel heaters, I wondered if this could be used as a whiteboard in the summer but you'd probably have to mount it so high it would be less useful as a heater!
https://www.screwfix.com/p/blyss-wall-mounted-glass-panel-heater-2000w/5412p

**Comment by johnmckerrell** [comment]
Thought I should add that we need definitely need whiteboards in this room. Findout have requested it but I was thinking if we have a lower down one that would be useful for when there's children there. A magnetic one would mean we could put magnetic letters on too.

**Comment by amcewen** [comment]
We've got a whiteboard installed now (and Ben has painted one on the wall too).  I've edited the description to include a list of all the things still to do (I think I've caught everything, but feel free to add any I've missed).

**Comment by magman2112** [comment]
Blinds now fitted.

**Comment by JackiePease** [comment]
Are people happy to close this (as we've moved Dinky)?
